---
- name: Ensure repo exists
  yum_repository:
    name: "varnishcache_varnish{{ varnishcache_version }}"
    description: Varnish Cache Daemon
    baseurl: "https://packagecloud.io/varnishcache/varnish{{ varnishcache_version }}/el/7/$basearch"
    gpgkey: "https://packagecloud.io/varnishcache/varnish{{ varnishcache_version }}/gpgkey"
    repo_gpgcheck: true
    gpgcheck: true
    sslverify: true
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300
    enabled: true

- name: Ensure epel-release is installed
  yum:
    name: epel-release
    state: installed
    
- name: Ensure varnish package is installed
  yum:
    name: varnish
    enablerepo: "varnishcache_varnish{{ varnishcache_version }}"
    state: latest