- name: Include RedHat/CentOS/etc specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  changed_when: false

- name: Set varnish_daemon fact
  set_fact:
    varnish_daemon: "{{ __varnish_daemon }}"
  when: varnish_daemon is not defined
  changed_when: false